# Template PHP Build

# Template PHP Build

# This template allows you to validate your PHP application.
# The workflow allows running tests and code linting on the default branch.

image: php:7.2.5
options:
  docker: true
  size: 2x

pipelines:
  default:
    - step:
        name: Sonar check quality code
        image: google/cloud-sdk:latest
        services:
            - docker
        size: 2x
        script:
        - pipe: sonarsource/sonarcloud-scan:1.4.0
          variables:
            SONAR_TOKEN: 'c5ce3306a23d30bf8d117808313c138d4209765c'

definitions:
  services:
    docker:
      memory: 4096
